ENVIRONMENT:
  MAX_EPISODE_STEPS: 5000
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False 
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SENSORS: ['GPS_SENSOR', 'COMPASS_SENSOR', 'OBJECTGOAL_PROMPT_SENSOR']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
  OBJECTGOAL_PROMPT_SENSOR:
    TYPE: "ObjectGoalPromptSensor"
    PROMPT: "{}"

DATASET:
  TYPE: ObjectNav-v2
  SPLIT: train
  DATA_PATH: "data/datasets/objectnav_mp3d_sample/{split}/{split}.json.gz"
  EPISODES_DIR: "data/datasets/objectnav_mp3d_sample/{split}/"
  SCENES_DIR: "data/scene_datasets/"
  MAX_REPLAY_BUFFER_STEPS: 2000
  # CONTENT_SCENES: ["Allensville.glb", "Pomaria.glb"]
